
instance_data_dir: '../instance_data-vqgan'
model:
  python_class: models.VQGAN.vqgan.VQModel
  params:
    embed_dim: 3
    n_embed: 16384
    ddconfig:
      double_z: False
      z_channels: 3
      resolution: 256
      in_channels: 3
      out_ch: 3
      ch: 128
      ch_mult: [ 1,1,2,4]  # num_down = len(ch_mult)-1
      num_res_blocks: 2
      attn_resolutions: []
      dropout: 0.0
    base_learning_rate: 4.5e-6
    training_batch_size: ${data.params.train.loader.batch_size}
    lossconfig:
      python_class: models.VQGAN.losses.vqperceptual.VQLPIPSWithDiscriminator
      params:
        disc_conditional: False
        disc_in_channels: 3
        disc_start: 30001
        disc_weight: 0.8
        codebook_weight: 1.0
data:
  python_class: utils.lightning.GenericDataModule.GenericDataModule
  params:
    train:
      python_class: datasets.Clevr_dataset.Clevr_dataset
      params:
        split: train
      loader:
        shuffle: true
        batch_size: 4
        num_workers: 4
    validation:
      python_class: datasets.Clevr_dataset.Clevr_dataset
      params:
        split: hard-val
      loader:
        shuffle: true
        batch_size: 4
        num_workers: 4
logger:
  python_class: lightning.pytorch.loggers.WandbLogger
  params:
    save_dir: ${instance_data_dir}
    project: lightning-ldm
    name: ldm-vqgan
trainer:
  max_epochs: 200 # override default
  strategy: ddp_find_unused_parameters_true
  callbacks:
    - python_class: utils.lightning.callbacks.VQGAN_image_logger.VQGAN_image_logger
      params:
        batch_frequency: 750
        max_images: 4
        clamp: true
